# Generated by Django 5.2.8 on 2025-11-22 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flightapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="flight",
            old_name="airline",
            new_name="airlines",
        ),
    ]
